version: "3"

services:
  voicepocket_apiserver:
    container_name: voicepocket_apiserver
    build:
      context: ./voicepocket
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://voicepocket_mysql:3306/voice_pocket
      SPRING_DATASOURCE_USERNAME: voice_docker
      SPRING_DATASOURCE_PASSWORD: voice!
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - voicePocket
    depends_on:
      - voicepocket_mysql

  voicepocket_mysql:
    image: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    container_name: voicepocket_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./celery_consumer/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment: #
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=voice_pocket
      - MYSQL_USER=voice_docker
      - MYSQL_PASSWORD=voice!
      - TZ=Asia/Seoul
    networks:
      - voicePocket

  rabbit:
      container_name: voicepocket_rabbitmq
      hostname: rabbit_example
      image: rabbitmq:3-management
      command: rabbitmq-server
      restart: unless-stopped
      environment:
        - RABBITMQ_DEFAULT_USER=sample
        - RABBITMQ_DEFAULT_PASS=sample!
        - RABBITMQ_DEFAULT_VHOST=rabbit_example
      ports:
        - 5672:5672
      networks:
        - voicePocket
      depends_on:
        - voicepocket_apiserver

  celery:
    container_name: voicepocket_celery
    build: 
      context: ./celery_consumer
    restart: unless-stopped
    depends_on:
      - "voicepocket_apiserver"
      - "rabbit"
    networks:
      - voicePocket
    command: ["celery", "-A", "celery_consume", "worker", "--loglevel=info"]
    volumes:
      - ./celery_consumer:/voice_pocket

  redis:
    image: redis:latest
    container_name: voicepocket_redis
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis/data:/data
    #   - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=voicepocket_redis"
      - "mode=standalone"
    networks:
      - voicePocket
    # restart: always
    command: redis-server # /usr/local/conf/redis.conf

networks:
  voicePocket:
    driver: bridge