name: Java CI with Gradle in smRt store

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main","develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x voicepocket/gradlew

      ## Move folder
      - name: Move Folder
        run: cd voicepocket

      ## Show Folder Detail
      - name: Show Folder Detail
        run: ls -alh

      ## Gradle Test를 실행한다
      - name: Test with Gradle
        run: gradlew --info test

      ## Test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'voicepocket/build/test-results/test/TEST-*.xml'

      ## 오류가 나는 부분에 코멘트를 달아줌
      - name: add comments to a pull request
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'voicepocket/build/test-results/test/TEST-*.xml'

